version: '3.8'
services:
  dev:
    container_name: hardcore_goldwasser
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
      - crystal-cache:/root/.cache/crystal
    ports:
      - "3000:3000"
    entrypoint: /app/entrypoint.sh
    command: sleep infinity
    working_dir: /app
volumes:
  crystal-cache:
